# Generated by Django 4.0.6 on 2022-11-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='name_field_value_x',
            field=models.CharField(choices=[('1', 'a'), ('2', 'b'), ('3', 'c')], default='name_field_value_x', max_length=50),
        ),
    ]
