# Generated by Django 4.0.6 on 2022-11-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_information_name_field_value_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='Enter_Name',
        ),
    ]
