# Generated by Django 4.0.6 on 2022-11-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_information_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='field_name',
            name='name_field_value_y',
            field=models.CharField(choices=[('1', 'k'), ('2', 'l'), ('3', 'm')], default='name_field_value_y', max_length=50),
        ),
    ]
